<!DOCTYPE html>
<html>
  <head>
    <title>ARIA Tooltip Example</title>
    <?php include("includes/common-head-tags.php"); ?>
    <link rel="stylesheet" type="text/css" href="css/tooltip.css" />
    <meta charset="utf-8" />
  </head>

  <body>
    <?php include("includes/example-header.php"); ?>

    <main>
      <h1>ARIA Tooltip Example</h1>

      <h2>JavaScript tooltips</h2>

      <aside class="notes">
        <h2>Notes:</h2>

        <ul>
          <li>Tooltips should be visible onfocus, and be hidden onblur.</li>
          <li>
            The widget that activates the tooltip should have an
            <code>aria-describedby</code> attribute that points to the tooltip
            so the AT can inform the user of it.
          </li>
        </ul>
      </aside>

      <p>
        <a role="tooltip" href="/" data-tooltip="This tooltip is accessible!"
          >This link has a tooltip</a
        >
        and so does this input field:
        <input
          role="tooltip"
          type="text"
          data-tooltip="You can put tooltips on any focusable item."
        />. The tooltip should be legible when in reading mode.
      </p>

      <h2>CSS only</h2>

      <aside class="notes">
        <h2>Notes:</h2>

        <ul>
          <li>These tooltips are implemented using the HTML <code>title</code> attribute
            and CSS generated content (i.e. <code>content: attr('title')</code>).</li>
          <li>Because of this, some screen-readers will read the tooltip twice.</li>
          <li>Note on hover, the default user-agent tooltip will appear.</li>
        </ul>
      </aside>

      <p>
        Here is a
        <a
          role="tooltip"
          class="has-css-only-tooltip"
          href="#"
          title="This is a tooltip generated by CSS only.  It will not work for form elements like input and textareas."
          >link with a CSS only tooltip</a
        >
        that read the title attribute. Note that this style of tooltip should
        work for buttons like this:
        <button
          role="tooltip"
          class="has-css-only-tooltip"
          title="CSS only tooltips are awesome."
        >
          Submit
        </button>
        They won't work on inputs:
        <input
          role="tooltip"
          type="text"
          class="has-css-only-tooltip"
          title="This tooltip shouldn't appear"
        />
      </p>
    </main>

    <script src="js/shared/tooltip.js"></script>
  </body>
</html>
