<div id="accessible-text-svg-demo">
  <div id="accessible-text-svg-demo__shape-container">
    <svg id="accessible-text-svg-demo__svg" xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0,0,1024,681">
      <defs>


        <path id="accessible-text-svg-demo__path1" fill="none" stroke="black" stroke-width="1"
          d="M 1, 431 C 479, 224, 502, 215, 779, 350 834, 386, 915, 493, 1023, 618">
        </path>
      </defs>


      <text id="accessible-text-svg-demo__intro-text" x="50" y="30">Good type…</text>
      <text id="accessible-text-svg-demo__text">


        <textpath id="accessible-text-svg-demo__svgTextPath" class="textpath"
          xlink:href="#accessible-text-svg-demo__path1" startOffset="20%">
          <tspan dy="0.1em">…needn't be flat!</tspan>
          <animate attributeName="startOffset" to="100%" begin="indefinite" dur="1s" repeatCount="1" id="rollout"
            fill="freeze"></animate>
          <animate attributeName="startOffset" to="1%" begin="indefinite" dur="1s" id="rollin" fill="freeze"></animate>

        </textpath>
      </text>

    </svg>

    <img id="accessible-text-svg-demo__roller-coaster-image" src="images/accessible-text-svg/roller-coaster.jpg"
      alt="Rollercoaster">



  </div>
  <button id="accessible-text-svg-demo__control">Animate Text</button>
</div>


<div class="with-full-bleed-hero__content">
  <h1><?= $title ?></h1>

  <?php includeStats(["isForNewBuilds" => true]); ?>
  <p>
    Consider the text that is overlaying the image below. You will notice that
    clicking the "Animate Text" button moves the text along the path of the roller
    coaster it overlays.
  </p>

  <p>
    This text complies with text spacing and text resizing requirements. If you use the
    text-spacing bookmarklet above, the text spaces out and doesn't get cut off.
  </p>

  <figure>
    <img src="images/accessible-text-svg/rollercoaster-screenshot__text-spacing.jpg"
      alt="A screen shot of the above demo showing the letter and word spacing increased.">
    <figcaption>
      Figure 1: The above demo with the text-spacing adjusted with the bookmarklet.
    </figcaption>
  </figure>

  <p>
    Using a couple of cross-browser tricks, this text also resizes well using the browser text-zooming
    functionality:
  </p>

  <figure>
    <img src="images/accessible-text-svg/rollercoaster-screenshot__zoom.jpg"
      alt="A screen shot of the above demo with the text zoomed to a factor of 200%">
    <figcaption>
      Figure 2: The above demo with the text zoomed to 200%.
    </figcaption>
  </figure>

  <p>
    The design also ensures that when text spacing is adjusted and text zoom to 200% is applied, the
    text is still fully visible.
  </p>

  <figure>
    <img src="images/accessible-text-svg/rollercoaster-screenshot__text-spacing-and-zoom.jpg"
      alt="A screen shot of the above demo with both increased text spacing and text zoom of 200% being applied.">
    <figcaption>
      Figure 3: The same demo with both text spacing and text zooming applied.
    </figcaption>
  </figure>

  <?php includeShowcode("accessible-text-svg-demo", "", "", "", true, 2); ?>
  <script type="application/json" id="accessible-text-svg-demo-props">
  {
    "replaceHtmlRules": {},
    "steps": [{
        "label": "Markup the SVG textpath",
        "highlight": "%OPENCLOSECONTENTTAG%svg ||| %OPENTAG%img",
        "notes": "The <code>img</code> tag is the photo of the roller coaster. The SVG has the curved text in it."
      },
      {
        "label": "Put the text inside a textpath tag",
        "highlight": "%OPENCLOSECONTENTTAG%textPath",
        "notes": "This is the text that will be sitting on top of the roller coaster track."
      },
      {
        "label": "Create the path the text should sit on top of.",
        "highlight": "%OPENCLOSECONTENTTAG%path",
        "notes": "The <code>d</code> attribute contains a bezier curve of the roller coaster's tracks. The curve was generated by <a href=\"https://www.useragentman.com/tests/textpath/bezier-curve-construction-set.html\">The SVG/VML Bézier Curve Construction Set</a> on my blog."
      },
      {
        "label": "Link the textpath and path elements together",
        "highlight": "xlink:href",
        "notes": "Because the two elements are linked this way, the text sits on top of the curve described by the <code>d</code> attribute of the <code>path</code> element."
      },
      {
        "label": "Ensure the CSS allows the text in the SVG to be resized",
        "highlight": "%CSS%accessible-text-css~ body ||| --text-zoom-factor:[^;]*; ||| %CSS%accessible-text-css~ #accessible-text-svg-demo__text ||| font-size:[^;]*;",
        "notes": [
          "<ul>",
          "  <li>You may think that, given the formula in the <code>calc</code> statement, that the text will not be zoomed at all, since the pixel value will always be multiplied by 1.  You'll see how this variable will change in the next step.</li>",
          "  <li>We usually use <code>rem</code> values for typography, but Firefox and Safari don't zoom text inside of SVGs, so we have to work around this using the JavaScript in the next step</li>",
          "</ul>"
        ]
      },
      {
        "label": "Insert text-zoom-event.js at the end of the document",
        "highlight": "%FILE% js/demos/accessible-text-svg.js ~ import\\stextZoomEvent[^;]*;",
        "notes": ""
      },
      {
        "label": "Use JavaScript to scale the text when uses the browser to zoom the text",
        "highlight": "%FILE% js/demos/accessible-text-svg.js ~  document.addEventListener[^;]*; ||| document.body.style.setProperty[^;]*;",
        "notes": "On textzoom, we ensure the font scales by the zoom factor calculated by the JavaScript library."
      },
      {
        "label": "Use JavaScript to alter other relevant parts of the SVG when text zoom is applied.",
        "highlight": "%FILE% js/demos/accessible-text-svg.js ~ pathEl.setAttribute[^;]*;",
        "notes": "If the text zoom is less than or equal to 1, we push the text a bit into the text path, so users can see the text curving over the roller coaster's \"hump\".  If the text zoom is greater than 1, we ensure that the text starts right at the beginning of the textpath, since we want to make sure there is enough room for the text when the text is scaled up."
      }
    ]
  }
  </script>
</div>