name: Automated Tests
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types: [opened, reopened]
    branches: ["main"]

jobs:
  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
          npm install @microsoft/eslint-formatter-sarif@2.1.7
      - name: Run ESLint
        run: npm run eslint
    #     continue-on-error: true
    #   - name: Upload analysis results to GitHub
    #     uses: github/codeql-action/upload-sarif@v2
    #     with:
    #       sarif_file: eslint-results.sarif
    #       wait-for-processing: true


#   tests:
#     name: Run Automated tests
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       security-events: write
#       actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Use Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20.11.0'
#           cache: 'npm'
#       - name: Install dependencies
#         run: npm ci
#       - name: Start server
#         run: npm run start
#       - name: Run tests
#         run: npm run test
    #   - name: Archive production artifacts
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: dist-without-markdown
    #       path: |
    #         dist
    #         !dist/**/*.md
    #   - name: Archive code coverage results
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: code-coverage-report
    #       path: output/test/code-coverage.html
